# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  
- task: CopyFiles@2
  displayName: 'Copy files to staging folder'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'  # Specify the path to your built files (e.g., dist folder)
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
- task: AzureFileCopy@6
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/*'
    azureSubscription: 'Gritty (9821a711-271f-4a7c-904d-a347fdc542a4)'
    Destination: 'AzureBlob'
    storage: '1hoodupads'
    ContainerName: '$web'
    CleanTargetBeforeCopy: true
- task: ArchiveFiles@2
  inputs:
    RootFolderOrFile: '$(build.artifactstagingdirectory)'  # Specify the root folder containing the files you want to include
    includeRootFolder: false  # Do not include the root folder in the archive
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
   
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  retryCountOnTaskFailure: 2
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

